---
default_stages:
  - commit
  - commit-msg

default_language_version:
  python: python3

repos:
  - hooks:
      - id: prepare-commit-message
        args: ["--format", "jira", "--jira-projects", "MLE"]
        stages: [commit-msg]
    repo: https://github.com/Lowess/pre-commit-hooks
    rev: v1.3.0 # Get the latest from: https://github.com/lowess/pre-commit-hooks/releases

  - hooks:
      - args:
          - "--safe"
        id: black
        language_version: python3
    repo: "https://github.com/ambv/black"
    rev: 18.9b0

  - hooks:
      - additional_dependencies:
          - black==18.9b0
        id: blacken-docs
        language_version: python3
    repo: "https://github.com/asottile/blacken-docs"
    rev: v0.3.0

  - hooks:
      - id: isort
        args:
          - --settings-path .
    repo: https://github.com/pycqa/isort
    rev: 5.6.0

  - hooks:
      - id: check-merge-conflict
      #- id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - additional_dependencies:
          - "flake8-bugbear == 18.2.0"
        id: flake8
        language_version: python3
    repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v2.4.0
